### ISSUE TITLE
03. 뷰 만들기: 자료형 선택 화면

### ISSUE THREAD

**Issue by ldj4245** [ldj4245/test-data#22]
이번 프로젝트에서 참고하고 있는 Mockaroo를 보면, 각 필드 자료형을 클릭할 때 큰 팝업을 볼 수 있다. 이를 구현하는 것을 검토한다.
 
## Todo
* [x]  관련 디자인 기술 조사하기
* [x]  구현이 필요한 기능 정리
   
   * 자료형을 모두 보여준다.
   * 자료형을 그룹별로 보여준다.
   * 자료형은 검색 가능해야 한다.
 * [x]  자료형 선택화면 구현 여부 의사결정
 
 ## Reference
 * https://www.mockaroo.com/
 * https://tailwindui.com/components/application-ui/overlays/modal-dialogs

**Comment by ldj4245** [comment]
위 사항을 개발 할 경우 프론트엔드 요소가 많이 포함되므로 개발하지 않기로 함.
